version: "3"
services:
    liquidity:
        container_name: liquidity
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./
        ports:
            - ${PORT}:8000